In [4]:

import pandas as pd

In [5]:
0%30

0

In [6]:
data_cnaes = pd.read_csv('../dados_brutos/F.K03200$Z.D60314.CNAECSV', sep=";", encoding='latin-1', header=None)
data_municipios = pd.read_csv('../dados_brutos/F.K03200$Z.D60314.MUNICCSV', sep=";", encoding='latin-1', header=None)
data_natureza_juridica = pd.read_csv('../dados_brutos/F.K03200$Z.D60314.NATJUCSV', sep=";", encoding='latin-1', header=None)
data_pais = pd.read_csv('../dados_brutos/F.K03200$Z.D60314.PAISCSV', sep=";", encoding='latin-1', header=None)

In [7]:
data_cnaes=data_cnaes.rename(columns={0:'codigo',1:'descricao_cnae'})
data_cnaes.head()

   codigo                                     descricao_cnae
0  111301                                   Cultivo de arroz
1  111302                                   Cultivo de milho
2  111303                                   Cultivo de trigo
3  111399  Cultivo de outros cereais não especificados an...
4  112101                        Cultivo de algodão herbáceo

In [8]:
data_municipios=data_municipios.rename(columns={0:'id',1:'municipio'})
data_municipios.head()

   id                municipio
0   1            GUAJARA-MIRIM
1   2  ALTO ALEGRE DOS PARECIS
2   3              PORTO VELHO
3   4                  BURITIS
4   5                JI-PARANA

In [9]:
data_natureza_juridica=data_natureza_juridica.rename(columns={0:'codigo','1':'descricao_natureza_juridica'})
data_natureza_juridica.head()

   codigo                                           1
0       0             Natureza Jurídica não informada
1    3271  Órgão de Direção Local de Partido Político
2    3280       Comitê Financeiro de Partido Político
3    3298        Frente Plebiscitária ou Referendária
4    3301                     Organização Social (OS)

In [10]:
data_pais=data_pais.rename(columns={0:'id',1:'pais'})
data_pais.head()

   id                   pais
0   0          COLIS POSTAUX
1  13            AFEGANISTAO
2  17                ALBANIA
3  20  ALBORAN-PEREJIL,ILHAS
4  23               ALEMANHA

In [11]:
data_empresa_cnpj=pd.read_csv('../dados_brutos/K3241.K03200Y0.D60314.ESTABELE',sep=";",usecols=[0,1,2,3,4,5,10,11,12,19,20],nrows=8000000,encoding='latin-1',header=None)

In [12]:
data_empresa_cnpj.head()

,0,1,2,3,4,5,10,11,12,19,20
0,37637816,1,30,1,AUTO MECANICA GUEDES,4,19930309,4520001,"4520002,4520003,4520004",GO,9373
1,1301519,1,72,1,ESCOLA ESTADUAL SILVA DOURADO,2,19960710,8550302,"8513900,8520100",TO,9247
2,57398075,1,90,1,NaN,8,19870507,5611201,NaN,SP,6291
3,20234118,1,91,1,BAR DE LOURDES,8,19780623,8888888,NaN,MG,4123
4,4682600,1,38,1,NaN,8,20010912,7020400,"8550301,8550302",SP,7047

In [13]:
data_empresa_cnpj.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000000 entries, 0 to 7999999
Data columns (total 11 columns):
 #   Column  Dtype
---  ------  -----
 0   0       int64
 1   1       int64
 2   2       int64
 3   3       int64
 4   4       str
 5   5       int64
 6   10      int64
 7   11      int64
 8   12      str
 9   19      str
 10  20      int64
dtypes: int64(8), str(3)
memory usage: 671.4 MB

In [14]:
# Creating the new columns of CNPJ
data_empresa_cnpj['cnpj']=data_empresa_cnpj[0].astype(str).str.zfill(8)+data_empresa_cnpj[1].astype(str).str.zfill(4)+data_empresa_cnpj[2].astype(str).str.zfill(2)

In [15]:
data_empresa_cnpj_reduzida=data_empresa_cnpj.drop(columns=[0,1,2])

In [16]:
data_empresa_cnpj_reduzida=data_empresa_cnpj_reduzida.rename(columns={3:"IDENTIFICADOR_MATRIZ/FILIAL",4:"NOME_FANTASIA",
                                           5:"SITUACAO_CADASTRAL",10:"DATA_DE_INÍCIO_ATIVIDADE",
                                           11:"CNAE_FISCAL_PRINCIPAL",12:"CNAE_FISCAL_SECUNDÁRIA",
                                           19:"UF",20:"MUNICÍPIO"})

In [17]:
data_empresa_cnpj_reduzida.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000000 entries, 0 to 7999999
Data columns (total 9 columns):
 #   Column                       Dtype
---  ------                       -----
 0   IDENTIFICADOR_MATRIZ/FILIAL  int64
 1   NOME_FANTASIA                str
 2   SITUACAO_CADASTRAL           int64
 3   DATA_DE_INÍCIO_ATIVIDADE     int64
 4   CNAE_FISCAL_PRINCIPAL        int64
 5   CNAE_FISCAL_SECUNDÁRIA       str
 6   UF                           str
 7   MUNICÍPIO                    int64
 8   cnpj                         str
dtypes: int64(5), str(4)
memory usage: 549.3 MB

In [18]:
data_municipios

        id                municipio
0        1            GUAJARA-MIRIM
1        2  ALTO ALEGRE DOS PARECIS
2        3              PORTO VELHO
3        4                  BURITIS
4        5                JI-PARANA
...    ...                      ...
5567  9989               SERRA ALTA
5568  9991                TUNAPOLIS
5569  9993                 GUARINOS
5570  9995               RIO QUENTE
5571  9997         CORONEL SAPUCAIA

[5572 rows x 2 columns]

In [19]:
data_empresa_cnpj_reduzida

,IDENTIFICADOR_MATRIZ/FILIAL,NOME_FANTASIA,SITUACAO_CADASTRAL,DATA_DE_INÍCIO_ATIVIDADE,CNAE_FISCAL_PRINCIPAL,CNAE_FISCAL_SECUNDÁRIA,UF,MUNICÍPIO,cnpj
0,1,AUTO MECANICA GUEDES,4,19930309,4520001,"4520002,4520003,4520004",GO,9373,37637816000130
1,1,ESCOLA ESTADUAL SILVA DOURADO,2,19960710,8550302,"8513900,8520100",TO,9247,01301519000172
2,1,NaN,8,19870507,5611201,NaN,SP,6291,57398075000190
3,1,BAR DE LOURDES,8,19780623,8888888,NaN,MG,4123,20234118000191
4,1,NaN,8,20010912,7020400,"8550301,8550302",SP,7047,04682600000138
...,...,...,...,...,...,...,...,...,...
7999995,1,NaN,8,19911209,4761001,NaN,RS,8561,94378080000167
7999996,1,A PERFUMARIA,4,19940915,4772500,"4723700,4753900",GO,9221,00196026000157
7999997,1,BAZAR LULU,4,19991028,4713002,NaN,SP,6213,03483556000174
7999998,1,CASA REUNIDA,4,19841213,4711301,NaN,PA,419,05140272000100
7999999,1,NaN,8,20020710,9511800,9529199,MS,9165,05140367000124

FIltrando empresas ativas

In [20]:
data_empresa_cnpj_reduzida_ativo=data_empresa_cnpj_reduzida.query("SITUACAO_CADASTRAL==2")

Verificando se existe 14 linha digitos no cnpj

In [21]:
data_empresa_cnpj_reduzida_ativo['cnpj'].str.len().value_counts()

cnpj
14    2977121
Name: count, dtype: int64

In [22]:
data_empresa_cnpj_reduzida_ativo.isnull().sum()

IDENTIFICADOR_MATRIZ/FILIAL          0
NOME_FANTASIA                  2095161
SITUACAO_CADASTRAL                   0
DATA_DE_INÍCIO_ATIVIDADE             0
CNAE_FISCAL_PRINCIPAL                0
CNAE_FISCAL_SECUNDÁRIA         1217082
UF                                   0
MUNICÍPIO                            0
cnpj                                 0
dtype: int64

In [23]:
data_empresa_cnpj_reduzida_ativo[data_empresa_cnpj_reduzida_ativo['NOME_FANTASIA'].isna()]

,IDENTIFICADOR_MATRIZ/FILIAL,NOME_FANTASIA,SITUACAO_CADASTRAL,DATA_DE_INÍCIO_ATIVIDADE,CNAE_FISCAL_PRINCIPAL,CNAE_FISCAL_SECUNDÁRIA,UF,MUNICÍPIO,cnpj
41,1,NaN,2,19830805,9499500,NaN,SC,9973,75434175000106
44,1,NaN,2,20040707,9430800,"9493600,9499500",MG,4701,06369406000122
49,2,NaN,2,19880127,4772500,NaN,SP,6425,58366832000378
58,2,NaN,2,19891208,4772500,NaN,SP,7083,58366832000882
65,1,NaN,2,19820507,9319199,NaN,SC,8131,75434605000190
...,...,...,...,...,...,...,...,...,...
7999916,1,NaN,2,19991027,8299799,"6399200,7410299,7490105,7490199,8219999,829970...",SP,7201,03475625000106
7999919,1,NaN,2,20020702,4712100,"4759899,4763601",SC,8345,05131553000105
7999933,1,NaN,2,20020617,8640202,"7739002,7820500,8211300",RJ,770,05133125000103
7999936,1,NaN,2,19940905,1412601,NaN,SP,7097,00190201000107
7999993,1,NaN,2,20020627,4110700,NaN,RJ,6001,05139796000181

In [24]:
data_empresa_cnpj_reduzida_ativo.dropna(inplace=True)

In [25]:
data_empresa_cnpj_reduzida_ativo.shape

(633856, 9)

In [26]:
data_empresa_cnpj_reduzida_ativo

,IDENTIFICADOR_MATRIZ/FILIAL,NOME_FANTASIA,SITUACAO_CADASTRAL,DATA_DE_INÍCIO_ATIVIDADE,CNAE_FISCAL_PRINCIPAL,CNAE_FISCAL_SECUNDÁRIA,UF,MUNICÍPIO,cnpj
1,1,ESCOLA ESTADUAL SILVA DOURADO,2,19960710,8550302,"8513900,8520100",TO,9247,01301519000172
78,1,POSTO SAO ROQUE NELORE,2,19930305,4731800,"4520001,4520003,4520004,4520006,4732600,561120...",GO,9445,37639036000120
79,1,NOSSO FOTO,2,19750107,4789008,"4619200,4743100,4759899,4789001,7420003",MA,803,06369474000191
86,1,ENDOGASTRO CLINICA DO APARELHO DIGESTIVO LTDA EPP,2,19981210,8610101,"8630501,8630502",SP,6979,02919792000128
139,1,EL SHADDAY CENTRO DE FORMACAO DE CONDUTORES (C...,2,19930304,8599601,8599602,GO,9373,37639812000191
...,...,...,...,...,...,...,...,...,...
7999880,1,IDEA AMBIENTACOES,2,19991026,4759801,"4754702,4754701,4754703,4789003",MA,921,03472205000168
7999942,1,ELETRO PONTO,2,19991021,4781400,"4754701,4753900",GO,9373,03478234000137
7999943,1,ATELIER EDMILSON MENEZES,2,19970507,4783101,4789001,PE,2531,01820963000102
7999958,1,MERCOSUL TURISMO,2,19970203,4929904,"4929902,7490104",RS,8507,01822286000153
7999981,1,COLEGIO SAGRADA FAMILIA,2,19970423,8513900,"8520100,8512100",AL,2835,01824485000109

In [27]:
data_empresa_cnpj_reduzida_ativo.isnull().sum()

IDENTIFICADOR_MATRIZ/FILIAL    0
NOME_FANTASIA                  0
SITUACAO_CADASTRAL             0
DATA_DE_INÍCIO_ATIVIDADE       0
CNAE_FISCAL_PRINCIPAL          0
CNAE_FISCAL_SECUNDÁRIA         0
UF                             0
MUNICÍPIO                      0
cnpj                           0
dtype: int64

## Verifiying  there  is a duplicates on CNPJ

In [28]:
data_empresa_cnpj_reduzida_ativo.duplicated().any()

np.False_

df['cnpj']

In [29]:
list_cnpj = data_empresa_cnpj_reduzida_ativo['cnpj'].head(500)

In [30]:
list_cnpj.to_csv('list_cnpj.csv',index=False)

In [32]:
data_empresa_cnpj_reduzida_ativo.to_csv('data_empresa_cnpj_reduzida_ativo.csv')